## array強化randn功能
讓只能生成平均0,標準差1的randn做出變化

平均50，標準差8

In [1]:
%matplotlib inline
import numpy as np
import matplotlib as plt

In [2]:
a = np.array(np.random.randn(50))
a

array([-0.45842006,  0.4570044 , -1.82789211, -0.51513697,  1.26540316,
       -0.58219144,  1.16084299, -1.59956691,  1.44782333,  0.32541342,
       -0.07310246, -0.38809187, -0.17578354, -0.67408987, -0.87870077,
       -1.0039547 ,  0.80935886, -0.24716888,  2.11856473,  0.92320889,
        1.73753102, -0.03418717,  1.04314031, -0.14602634,  1.34750915,
        0.83267686, -1.49795214, -0.5871169 ,  2.23602539, -0.12367891,
       -0.69067447,  1.38153532, -0.05140209, -0.00962298,  0.57102586,
        1.65413962, -1.46865249,  1.68847401, -0.15780399,  0.43788411,
        0.44430695, -0.0470539 ,  0.03904703, -1.48758226,  1.46587268,
        0.08632644,  0.09818448,  1.99880145,  1.15069516,  0.49916082])

In [3]:
new_a = (a * 8) + 50
new_a

array([46.33263956, 53.65603521, 35.37686314, 45.87890424, 60.12322528,
       45.34246845, 59.28674396, 37.20346471, 61.58258661, 52.60330735,
       49.41518035, 46.89526502, 48.59373167, 44.60728101, 42.97039383,
       41.9683624 , 56.47487084, 48.02264894, 66.94851787, 57.38567113,
       63.90024817, 49.72650267, 58.34512247, 48.83178926, 60.78007322,
       56.66141487, 38.01638286, 45.30306478, 67.88820315, 49.01056872,
       44.47460426, 61.05228257, 49.58878329, 49.92301619, 54.56820688,
       63.23311698, 38.25078009, 63.50779207, 48.7375681 , 53.50307286,
       53.55445561, 49.6235688 , 50.31237624, 38.09934192, 61.72698145,
       50.69061155, 50.78547582, 65.99041159, 59.20556129, 53.99328655])

## 改變array的形狀(維度)
shape 直接改變造型
reshape 改變造型後賦予新的 array

In [5]:
b = a.reshape(5,10)
print(a)
print(b)

[-0.45842006  0.4570044  -1.82789211 -0.51513697  1.26540316 -0.58219144
  1.16084299 -1.59956691  1.44782333  0.32541342 -0.07310246 -0.38809187
 -0.17578354 -0.67408987 -0.87870077 -1.0039547   0.80935886 -0.24716888
  2.11856473  0.92320889  1.73753102 -0.03418717  1.04314031 -0.14602634
  1.34750915  0.83267686 -1.49795214 -0.5871169   2.23602539 -0.12367891
 -0.69067447  1.38153532 -0.05140209 -0.00962298  0.57102586  1.65413962
 -1.46865249  1.68847401 -0.15780399  0.43788411  0.44430695 -0.0470539
  0.03904703 -1.48758226  1.46587268  0.08632644  0.09818448  1.99880145
  1.15069516  0.49916082]
[[-0.45842006  0.4570044  -1.82789211 -0.51513697  1.26540316 -0.58219144
   1.16084299 -1.59956691  1.44782333  0.32541342]
 [-0.07310246 -0.38809187 -0.17578354 -0.67408987 -0.87870077 -1.0039547
   0.80935886 -0.24716888  2.11856473  0.92320889]
 [ 1.73753102 -0.03418717  1.04314031 -0.14602634  1.34750915  0.83267686
  -1.49795214 -0.5871169   2.23602539 -0.12367891]
 [-0.69067447  1.

In [6]:
a.shape = (5,10)
a

array([[-0.45842006,  0.4570044 , -1.82789211, -0.51513697,  1.26540316,
        -0.58219144,  1.16084299, -1.59956691,  1.44782333,  0.32541342],
       [-0.07310246, -0.38809187, -0.17578354, -0.67408987, -0.87870077,
        -1.0039547 ,  0.80935886, -0.24716888,  2.11856473,  0.92320889],
       [ 1.73753102, -0.03418717,  1.04314031, -0.14602634,  1.34750915,
         0.83267686, -1.49795214, -0.5871169 ,  2.23602539, -0.12367891],
       [-0.69067447,  1.38153532, -0.05140209, -0.00962298,  0.57102586,
         1.65413962, -1.46865249,  1.68847401, -0.15780399,  0.43788411],
       [ 0.44430695, -0.0470539 ,  0.03904703, -1.48758226,  1.46587268,
         0.08632644,  0.09818448,  1.99880145,  1.15069516,  0.49916082]])